# Generated by Django 3.2.7 on 2021-10-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('house', models.CharField(max_length=20, verbose_name='Дом')),
                ('opening_time', models.TimeField(verbose_name='Время открытия')),
                ('closing_time', models.TimeField(verbose_name='Время закрытия')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.street', verbose_name='Улица')),
            ],
        ),
    ]
